Feature/icons
jahorwitz/mu-methods pull request #76
Opened 2023-03-01 16:11 UTC by NuriyaAkh

## Describe your changes

## Issue ticket number and link

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] If there are changes to components, I have added / updated automated tests
- [ ] I have made any necessary updates to Storybook to accompany these changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-03-01 16:13 UTC, NuriyaAkh commented
Settings icon is not rendering correctly

2023-03-02 01:22 UTC, jahorwitz requested changes
Just one change, but it'll be in several places:

Could you please implement a standard for all of these icons that each of them accepts props for `className`, `width` (default to `"16"`), `height` (also default to `"16"`), and pass those props to the `<svg` element? This will make these icons just a bit more flexible. For any of the ones we are currently using, make sure to pass in values to override the defaults if needed. I made a comment for `add.jsx` to show an example of what I mean.

2023-03-02 01:22 UTC, jahorwitz commented on src/components/icons/add.jsx
> +      height="14"
```suggestion
const Add = ({className, width = "16", height = "16" }) => {
  return (
    <svg
      width={width}
      height={height}
      className={className}
```

2023-03-02 19:40 UTC, kamal-ganiev commented
Leaving a comment for changes made on last commit:
1. Add "active" attribute to Home, Profile and Notifications
2. Add conditional statement for fill-opacity.
3. Change names of components to avoid match naming with another components ( ex. Home to HomeIcon, <Home /> already exists as layout ).
4. Remove nav-tray-icons component, because we don't need it anymore.

2023-03-02 21:08 UTC, kamal-ganiev approved these changes
Thank you for changing names back, the only thing, we might need to remove nav-link-icon, since we get Profile icon from corresponding file.

2023-03-03 00:28 UTC, jahorwitz approved these changes

2023-03-03 00:51 UTC, merged